# Welcome to Jekyll!
#
# This config file is meant for settings that affect your entire site, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# `jekyll serve`. If you change this file, please restart the server process.

# Site Settings

theme: jekyll-theme-cayman
title: "Nelson Kiyoshi Kossuga"
title_separator          : "-"
name                     : &name "Nelson Kiyoshi Kossuga"
description: &description "Games Programmer, Graphics Enthusiast"
